# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: meta
  hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: '\.tf$'
    -   id: check-yaml
        args:
          - --allow-multiple-documents
    -   id: check-added-large-files
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.19.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_validate
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.12.6
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.0.9
  hooks:
    - id: shellcheck
